@startuml RMQ

sprite $RMQ [90x90/color] {
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!zzzzzzzzzzzzzzzzzzzzzzzz!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!zzzzzzzzzzzzzzzzzzzzzzzz!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!W:ivrRrRrRrRrRrRrRrRrRrRmvaM!!!!!!!!!!!!!!!!!!!!!!!!!!!!W:iurRrRrRrRrRrRrRrRrRrRmvW:!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!Vrvhzzzyzyzyzyzyzyzyzyzyzyzzviiv~&!!!!!!!!!!!!!!!!!!!!zzeevizzzyzyzyzyzyzyzyzyzyzyzzviivJJ!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!JJrRzhybu%u%u%u%u%u%u%u%u%u%yazQvin>zz!!!!!!!!!!!!!!!!!!eerRzhybu%u%u%u%u%u%u%u%u%u%uazQviee!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!aNzzystltmtmtmtmtmtmtmtmtmtmtlyazhn>W:zz!!!!!!!!!!!!!!!!aMziystltmtmtmtmtmtmtmtmtmtmtluKzhivaNzz!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tmtmtmtmtmtmtmtmtmtmtmtmu%zQr>ivzz!!!!!!!!!!!!zz!!ieziuJtltmtmtmtmtmtmtmtmtmtmtmu%zQnRrRzz!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!n>zyu&tmtmtmtmtmtmtmtmtmtmtmtmu%zQrQivzz!!!!!!!!!!!!zz!!ivziuJtltmtmtmtmtmtmtmtmtmtmtmu%zQrRjR!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmu%zQn>ivzz!!!!!!!!!!!!zz!!iuziuJtltmtmtmtmtmtmtmtmtmtmtmu%zQrRiv!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmu%zQn>ivzz!!!!!!!!!!!!zz!!iuziuJtltmtmtmtmtmtmtmtmtmtmtmu%zQrRiv!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmu%zQn>ivzz!!!!!!!!!!!!zz!!iuziuJtltmtmtmtmtmtmtmtmtmtmtmu%zQrRiv!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmu%zQn>ivzz!!!!!!!!!!!!zz!!iuziuJtltmtmtmtmtmtmtmtmtmtmtmu%zQrRiv!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmu%zQn>ivzz!!!!!!!!!!!!zz!!iuziuJtltmtmtmtmtmtmtmtmtmtmtmu%zQrRiv!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmu%zQn>ivzz!!!!!!!!!!!!zz!!iuziuJtltmtmtmtmtmtmtmtmtmtmtmu%zQrRiv!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmu%zQn>ivzz!!!!!!!!!!!!zz!!iuziuJtltmtmtmtmtmtmtmtmtmtmtmu%zQrRiv!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmu%zQn>ivzz!!!!!!!!!!!!zz!!iuziuJtltmtmtmtmtmtmtmtmtmtmtmu%zQrRiv!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmu%zQn>ivzz!!!!!!!!!!!!zz!!iuziuJtltmtmtmtmtmtmtmtmtmtmtmu%zQrRiv!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmu%zQn>ivzz!!!!!!!!!!!!zz!!iuziuJtltmtmtmtmtmtmtmtmtmtmtmu%zQrRiv!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmu%zQn>ivzz!!!!!!!!!!!!zz!!iuziuJtltmtmtmtmtmtmtmtmtmtmtmu%zQrRiv!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmu%zQn>ivzz!!!!!!!!!!!!zz!!iuziuJtltmtmtmtmtmtmtmtmtmtmtmu%zQrRiv!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmu%zQn>ivzz!!!!!!!!!!!!zz!!iuziuJtltmtmtmtmtmtmtmtmtmtmtmu%zQrRiv!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmu%zQn>ivzz!!!!!!!!!!!!zz!!iuziuJtltmtmtmtmtmtmtmtmtmtmtmu%zQrRiv!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmu%zQn>ivzz!!!!!!!!!!!!zz!!iuziuJtltmtmtmtmtmtmtmtmtmtmtmu%zQrRiv!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmu%zQn>ivzz!!!!!!!!!!!!zz!!iuziuJtltmtmtmtmtmtmtmtmtmtmtmu%zQrRiv!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmu%zQn>ivzz!!!!!!!!!!!!zz!!iuziuJtltmtmtmtmtmtmtmtmtmtmtmu%zQrRiv!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmu%zQn>ivzz!!!!!!!!!!!!zz!!iuziuJtltmtmtmtmtmtmtmtmtmtmtmu%zQrRiv!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmu%zQn>ivzz!!!!!!!!!!!!zz!!iuziuJtltmtmtmtmtmtmtmtmtmtmtmu%zQrRiv!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmu%zQrQivzz!!!!!!!!!!!!zz!!iuziuJtltmtmtmtmtmtmtmtmtmtmtmu%zQrRiv!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmu%zQn>n<zzzzzzzzzzzzzzzzzzieziuJtltmtmtmtmtmtmtmtmtmtmtmu%zQrRnRzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmu%zPrRn>!!!!!!!!!!!!!!!!!!ivzhuItltmtmtmtmtmtmtmtmtmtmtmu%zQrRrR!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmz;zyrRn>n>rRrRrRrRr>r>rRzzzQu$tmtmtmtmtmtmtmtmtmtmtmtmtmytzyrRn>rRrRrRrRrRrRrRrRrRrRrRrRrRrRrRrQrQrQrQn>n>n>iuee!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmu%z;zhzhzhzhzhzhzhzhzhzhzPu&tmtmtmtmtmtmtmtmtmtmtmtmtmtmu%z;zhzhzhzhzhzhzhzhzhzhzhzhzhzhzhzhzhzhzhzhzhzhzhzhziviivJJ!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmtmtmu%u&u&u&u&u&u&u&u&u%tmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmu%u&u&u&u&u&u&u&u&u&u&u&u&u&u&u&u&u&u&u&u&u&u&u&yazQviaN!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtluJzin>!!zz!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmu$zhrR!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmzhrR!!zz!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmzhrR!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmzhrR!!zz!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmzhrR!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmzhrR!!zz!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmzhrR!!zz!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmzhrR!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmzhrR!!zz!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmzhrR!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmzhrR!!zz!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmu%u&u&u&u&u&u&u%tmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmzhrR!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmu%ytzQzhzhzhzhzhzhzQz<uItmtmtmtmtmtmtmtmtmtmtmtmtmtmtmzhrR!!zz!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmu%zPzyzzzzzzzzzzzzzzzzzzzhyJtmtmtmtmtmtmtmtmtmtmtmtmtmtmzhrR!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmyszyzzzzzzzzzzzzzzzzzzzzzzzPu$tmtmtmtmtmtmtmtmtmtmtmtmtmzhrR!!zz!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmu$zQzzzzzzzzzzzzzzzzzzzzzzzzzhuItmtmtmtmtmtmtmtmtmtmtmtmtmzhrR!!zz!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmu%zQzzzzzzzzzzzzzzzzzzzzzzzzzhyJtltmtmtmtmtmtmtmtmtmtmtmtmzhrR!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmu%zQzzzzzzzzzzzzzzzzzzzzzzzzzhyJtltmtmtmtmtmtmtmtmtmtmtmtmzhrR!!zz!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmu%zQzzzzzzzzzzzzzzzzzzzzzzzzzhyJtltmtmtmtmtmtmtmtmtmtmtmtmzhrR!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmu%zQzzzzzzzzzzzzzzzzzzzzzzzzzhyJtltmtmtmtmtmtmtmtmtmtmtmtmzhrR!!zz!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmu%zQzzzzzzzzzzzzzzzzzzzzzzzzzhyJtltmtmtmtmtmtmtmtmtmtmtmtmzhrR!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmu%zQzzzzzzzzzzzzzzzzzzzzzzzzzhyJtltmtmtmtmtmtmtmtmtmtmtmtmzhrR!!zz!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmu$zQzzzzzzzzzzzzzzzzzzzzzzzzzhuJtmtmtmtmtmtmtmtmtmtmtmtmtmzhrR!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmytzyzzzzzzzzzzzzzzzzzzzzzzzPu%tmtmtmtmtmtmtmtmtmtmtmtmtmzhrR!!zz!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmu%zQzyzzzzzzzzzzzzzzzzzzzhyJtmtmtmtmtmtmtmtmtmtmtmtmtmtmzhrR!!zz!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmu%z;zQzhzhzhzhzhzhzQz=yJtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmzhrR!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmu&uIuIuIuIuIuIu&u$tmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmzhrR!!zz!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmzhrR!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmzhrR!!zz!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmzhrR!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmzhrR!!zz!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmzhrR!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmzhrR!!zz!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmzhrR!!zz!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmzhrR!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tltmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmzhrR!!zz!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmzhrR!!!!!!!!!!!!!!!!
!!!!!!!!!!!!zz!!ivzyu&tmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmzhrR!!zz!!!!!!!!!!!!
!!!!!!!!!!!!zz!!W:zzybtltmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtmtluJziiv!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!~&n>zhybu%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%uJzQvRRr!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!NJn>zyzizizizizizizizizizizizizizizizizizizizizizizizizizizizizizizizizizizizizizizizizizizizizizizizizizizizizizizizizizizizizizizizizizizirRW:~&!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!J&W:ivivivivivivivivivivivivivivivivivivivivivivivivivivivivivivivivivivivivivivivivivivivivivivivivivivivivivivivivivivivivivivivivivivaNJJ>n!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
}

sprite $RMQ16 [90x90/16] {
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFF000000000000FFFFFFFFFFFFFFFF000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFF74211111111236FFFFFFFFFFFFFF74211111111237FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFF8100000000000014BFFFFFFFFFF05100000000000014AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFA104666666666641130FFFFFFFFF520366666666664115FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF0F60376666666666741370FFFFFFFF60376666666666740460FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF0F30566666666666651240FFFFFF0F40566666666666661220FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF0F30566666666666661240FFFFFF0F4056666666666666122FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF0F30566666666666661240FFFFFF0F4056666666666666124FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF0F30566666666666661240FFFFFF0F4056666666666666124FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF0F30566666666666661240FFFFFF0F4056666666666666124FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF0F30566666666666661240FFFFFF0F4056666666666666124FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF0F30566666666666661240FFFFFF0F4056666666666666124FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF0F30566666666666661240FFFFFF0F4056666666666666124FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF0F30566666666666661240FFFFFF0F4056666666666666124FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF0F30566666666666661240FFFFFF0F4056666666666666124FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF0F30566666666666661240FFFFFF0F4056666666666666124FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF0F30566666666666661240FFFFFF0F4056666666666666124FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF0F30566666666666661240FFFFFF0F4056666666666666124FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF0F30566666666666661240FFFFFF0F4056666666666666124FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF0F30566666666666661240FFFFFF0F4056666666666666124FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF0F30566666666666661240FFFFFF0F4056666666666666124FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF0F30566666666666661240FFFFFF0F4056666666666666124FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF0F30566666666666661240FFFFFF0F4056666666666666124FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF0F30566666666666661240FFFFFF0F4056666666666666124FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF0F30566666666666661240FFFFFF0F4056666666666666124FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF0F30566666666666661240FFFFFF0F4056666666666666124FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF0F30566666666666661240FFFFFF0F4056666666666666124FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF0F30566666666666651230000000004056666666666666122000000000000000000000000FFFFFFFFFFF
FFFFFF0F3056666666666666123FFFFFFFFF4056666666666666121FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFF0F305666666666666630122222222201666666666666663022222222222222222222222245FFFFFFFFFF
FFFFFF0F3056666666666666621000000000156666666666666662100000000000000000000000014AFFFFFFFF
FFFFFF0F30566666666666666665555555556666666666666666666555555555555555555555554115FFFFFFFF
FFFFFF0F30566666666666666666666666666666666666666666666666666666666666666666667403F0FFFFFF
FFFFFF0F30566666666666666666666666666666666666666666666666666666666666666666666602FFFFFFFF
FFFFFF0F30566666666666666666666666666666666666666666666666666666666666666666666601F0FFFFFF
FFFFFF0F30566666666666666666666666666666666666666666666666666666666666666666666601FFFFFFFF
FFFFFF0F30566666666666666666666666666666666666666666666666666666666666666666666601F0FFFFFF
FFFFFF0F30566666666666666666666666666666666666666666666666666666666666666666666601FFFFFFFF
FFFFFF0F30566666666666666666666666666666666666666666666666666666666666666666666601F0FFFFFF
FFFFFF0F30566666666666666666666666666666666666666666666666666666666666666666666601F0FFFFFF
FFFFFF0F30566666666666666666666666666666666666666666666666666666666666666666666601FFFFFFFF
FFFFFF0F30566666666666666666666666666666666666666666666666666666666666666666666601F0FFFFFF
FFFFFF0F30566666666666666666666666666666666666666666666666666666666666666666666601FFFFFFFF
FFFFFF0F30566666666666666666666666666666666666666666666666666666666666666666666601F0FFFFFF
FFFFFF0F30566666666666666666666666666666666666666666666655555566666666666666666601FFFFFFFF
FFFFFF0F30566666666666666666666666666666666666666666663111111112566666666666666601F0FFFFFF
FFFFFF0F30566666666666666666666666666666666666666666610000000000156666666666666601FFFFFFFF
FFFFFF0F30566666666666666666666666666666666666666666300000000000026666666666666601F0FFFFFF
FFFFFF0F30566666666666666666666666666666666666666666100000000000015666666666666601F0FFFFFF
FFFFFF0F30566666666666666666666666666666666666666666100000000000015666666666666601FFFFFFFF
FFFFFF0F30566666666666666666666666666666666666666666100000000000014666666666666601F0FFFFFF
FFFFFF0F30566666666666666666666666666666666666666666100000000000014666666666666601FFFFFFFF
FFFFFF0F30566666666666666666666666666666666666666666100000000000014666666666666601F0FFFFFF
FFFFFF0F30566666666666666666666666666666666666666666100000000000014666666666666601FFFFFFFF
FFFFFF0F30566666666666666666666666666666666666666666100000000000015666666666666601F0FFFFFF
FFFFFF0F30566666666666666666666666666666666666666666100000000000015666666666666601FFFFFFFF
FFFFFF0F30566666666666666666666666666666666666666666300000000000016666666666666601F0FFFFFF
FFFFFF0F30566666666666666666666666666666666666666666610000000000146666666666666601F0FFFFFF
FFFFFF0F30566666666666666666666666666666666666666666652111111112566666666666666601FFFFFFFF
FFFFFF0F30566666666666666666666666666666666666666666666555555556666666666666666601F0FFFFFF
FFFFFF0F30566666666666666666666666666666666666666666666666666666666666666666666601FFFFFFFF
FFFFFF0F30566666666666666666666666666666666666666666666666666666666666666666666601F0FFFFFF
FFFFFF0F30566666666666666666666666666666666666666666666666666666666666666666666601FFFFFFFF
FFFFFF0F30566666666666666666666666666666666666666666666666666666666666666666666601F0FFFFFF
FFFFFF0F30566666666666666666666666666666666666666666666666666666666666666666666601FFFFFFFF
FFFFFF0F30566666666666666666666666666666666666666666666666666666666666666666666601F0FFFFFF
FFFFFF0F30566666666666666666666666666666666666666666666666666666666666666666666601F0FFFFFF
FFFFFF0F30566666666666666666666666666666666666666666666666666666666666666666666601FFFFFFFF
FFFFFF0F30566666666666666666666666666666666666666666666666666666666666666666666601F0FFFFFF
FFFFFF0F30566666666666666666666666666666666666666666666666666666666666666666666601FFFFFFFF
FFFFFF0F40566666666666666666666666666666666666666666666666666666666666666666666602F0FFFFFF
FFFFFF0F70376666666666666666666666666666666666666666666666666666666666666666667504FFFFFFFF
FFFFFFFFB2146666666666666666666666666666666666666666666666666666666666666666665118FFFFFFFF
FFFFFFFFFA20000000000000000000000000000000000000000000000000000000000000000000017BFFFFFFFF
FFFFFFFFFFB74344444444444444444444444444444444444444444444444444444444444444346ACFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
}

sprite $RMQ16z [90x90/16z] {
xTPLaiD038HXjMZ2klzf5yqEUxoexrLLVtKuSLjAD73ZzbCKPJHO_Cgjn6Cse07eFZfaazik7h03gNSK48gMCSdePd4t2YSftYaAALrwUYDrkhyiP3vWOANs
fkERW_dvijyenrfb_SlbB6SvordESfODBDIQbvakk6kpH6jUne9dGmZS8lZanXUetIuxWremltIRWkukbdlMyZaxJm6xK5weA4bGpNAFE6AbCe9MAu_avl_z
REHc-r1_iw31LdSpg0EhkLbeW6jk1Wt0lguSjSgwscRDpR_klI6ZycgVRgrQDaQ3hVRtipNoDoKtvx-l7xzPQvLvkhcG55-i66bCx1dgYncmYQaTKmKe-vZP
5nLTHDHtX_YBKde5
}

sprite $RMQ8 [90x90/8] {
__________________________________________________________________________________________
__________________________________________________________________________________________
__________________________________________________________________________________________
___________777777777777________________777777777777_______________________________________
_________yOG80000000088Owz__________uwOG80000000088Owz____________________________________
______u_h01JRRRRRRRRRRJ2093u________J81BRRRRRRRRRRJ20Ixu__________________________________
______0_90IRRRRRRRRRRRRJ09I0______0_I0IRRRRRRRRRRRRR0997__________________________________
______0_90IRRRRRRRRRRRRR09I0______0_I0IRRRRRRRRRRRRR09I___________________________________
______0_90IRRRRRRRRRRRRR09I0______0_I0IRRRRRRRRRRRRR09I___________________________________
______0_90IRRRRRRRRRRRRR09I0______0_I0IRRRRRRRRRRRRR09I___________________________________
______0_90IRRRRRRRRRRRRR09I0______0_I0IRRRRRRRRRRRRR09I___________________________________
______0_90IRRRRRRRRRRRRR09I0______0_I0IRRRRRRRRRRRRR09I___________________________________
______0_90IRRRRRRRRRRRRR09I0______0_I0IRRRRRRRRRRRRR09I___________________________________
______0_90IRRRRRRRRRRRRR09I0______0_I0IRRRRRRRRRRRRR09I___________________________________
______0_90IRRRRRRRRRRRRR09I0______0_I0IRRRRRRRRRRRRR09I___________________________________
______0_90IRRRRRRRRRRRRR09I0______0_I0IRRRRRRRRRRRRR09I___________________________________
______0_90IRRRRRRRRRRRRR09I0______0_I0IRRRRRRRRRRRRR09I___________________________________
______0_90IRRRRRRRRRRRRJ099777777777I0IRRRRRRRRRRRRR098777777777777777777777777___________
______0_90IRRRRRRRRRRRRRB1088888888802RRRRRRRRRRRRRRB1888888888888888888888888GGwz________
______0_90IRRRRRRRRRRRRRRRRJJJJJJJJJRRRRRRRRRRRRRRRRRRRJJJJJJJJJJJJJJJJJJJJJJJJ20H_u______
______0_90IRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR08_u______
______0_90IRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR00_u______
______0_90IRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR00_u______
______0_90IRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR00_7______
______0_90IRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR00_7______
______0_90IRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRQQQQQQRRRRRRRRRRRRRRRRRR00_7______
______0_90IRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRO8000000008GQRRRRRRRRRRRRRR00_7______
______0_90IRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR80000000000008QRRRRRRRRRRRRR00_0______
______0_90IRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR00000000000000IRRRRRRRRRRRRR00_u______
______0_90IRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR00000000000000IRRRRRRRRRRRRR00_u______
______0_90IRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR00000000000000IRRRRRRRRRRRRR00_u______
______0_90IRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR10000000000000JRRRRRRRRRRRRR00_u______
______0_90IRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR210000000012JRRRRRRRRRRRRRR00_7______
______0_90IRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRJJJJJJJJRRRRRRRRRRRRRRRRR00_7______
______0_90IRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR00_7______
______0_90IRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR00_7______
______0_90IRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR00_0______
______0_90IRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR00_u______
______0_A0IRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR01_u______
______7_T18QRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRQG0K________
_________lD321222222222222222222222222222222222222222222222222222222222222221235Ul________
__________________________________________________________________________________________
__________________________________________________________________________________________
__________________________________________________________________________________________
__________________________________________________________________________________________
}

sprite $RMQ8z [90x90/8z] {
xTO5ZWCn44JHWdZx_YTU7dHWm5xi9rPBNnLEF9OIPXxSVWgB-4JwuMsx2nPKOWJLj-qA88y4434GmSLDiHd2e6S4UaZNDndRouHMPM6uQNapoEDbFoX7hxB-
SZdBMSvobhESPO74e2uJDspQp1ZKPPnuDWXm07XrumtIuxA9YLpTRb5vMBOrS4qt0BfHFajWe4lPOAVD1WBToWkv-Ny_6xbPxzfl9ZvHRJTZHYqt4pDikHaB
-hho83VdvbwV5FJxT3Sjg_f6QlVzh4_vcvARyz_NZz-iLcMkDnjq0u9YfH1g4SObwZHQS8bAiQXJA9Ud-8jIUW4
}

sprite $RMQ4 [90x90/4] {
__________________________________________________________________________________________
__________________________________________________________________________________________
__________zDCCCCCCCCCCCz______________zDCCCCCCCCCCCz______________________________________
______y_vW05555555555551GWny________5G01555555555551Gbzy__________________________________
______0_00LLLLLLLLLLLLLL00L0______0_L0LLLLLLLLLLLLLL001F__________________________________
______0_00LLLLLLLLLLLLLL00L0______0_L0LLLLLLLLLLLLLL00L___________________________________
______0_00LLLLLLLLLLLLLL00L0______0_L0LLLLLLLLLLLLLL00L___________________________________
______0_00LLLLLLLLLLLLLL00L0______0_L0LLLLLLLLLLLLLL00L___________________________________
______0_00LLLLLLLLLLLLLL00L0______0_L0LLLLLLLLLLLLLL00L___________________________________
______0_00LLLLLLLLLLLLLL00L0______0_L0LLLLLLLLLLLLLL00L___________________________________
______0_00LLLLLLLLLLLLLL00L0______0_L0LLLLLLLLLLLLLL00L___________________________________
______0_00LLLLLLLLLLLLLL00G3pppppp3pL0LLLLLLLLLLLLLL00Gpppppppppppppppppppppppp___________
______0_00LLLLLLLLLLLLLL51111111111115LLLLLLLLLLLLLL51111111111111111111111111HGqv________
______0_00LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL00_C______
______0_00LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL00_p______
______0_00LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL00_3______
______0_00LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL00_C______
______0_00LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLKGGGGGGGGGGKLLLLLLLLLLLLLLL00_p______
______0_00LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL00000000000000LLLLLLLLLLLLLL00_3______
______0_00LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL00000000000000LLLLLLLLLLLLLL00_C______
______0_00LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL00000000000000LLLLLLLLLLLLLL00_p______
______0_00LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL51000000000015LLLLLLLLLLLLLL00_3______
______0_00LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL00_C______
______0_00LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL00_p______
______0_00LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL00_3______
______0_10LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL00_C______
______F_R20KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKG1Q________
__________lVVFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVFVVl__________
__________________________________________________________________________________________
__________________________________________________________________________________________
}

sprite $RMQ4z [90x90/4z] {
xPP7SiH03CGQvF__xCkcCLUPuzYuTXKAoifjZD4BkxRl1_I4pMq_eG7YEOc5RQ-O5uRpYORnKBKIYL7DNLqtq7wpn89PITaqpvoppFnniyqsssoppJO_AUPb
zfdpJlEtUs1lCsoRAU9TQX7LJ0SIayn8gMbcD-FcYi-6c_MWkLalj3Phe3R_GdF-acOtkxcgwJ5NzVzzFxlPVr--WanhfYbQv2UYnon5LdKBH1O2n2K4aNyI
Opu
}


BKEntityColoring(RMQ)
!define RMQ(e_alias, e_label, e_techn) BKEntity(e_alias, e_label, e_techn, #00000000, RMQ, RMQ)
!define RMQ(e_alias, e_label, e_techn, e_descr) BKEntity(e_alias, e_label, e_techn, e_descr, #00000000, RMQ, RMQ)
!define RMQParticipant(p_alias, p_label, p_techn) BKParticipant(p_alias, p_label, p_techn, #000000, RMQ, RMQ)
!define RMQParticipant(p_alias, p_label, p_techn, p_descr) BKParticipant(p_alias, p_label, p_techn, p_descr, #000000, RMQ, RMQ)

@enduml